---
title: "Fig 1C"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r, include=F}
#library(cdsr)
#library(taigr)
library(useful)
library(tidyverse)
library(magrittr)
library(corrplot)
library(here)
library(ggplot2)

source(here::here('src', 'helper_functions.R'))
```

## Achilles
```{r}
Achilles.gene.effect.CRISPR <- data.table::fread(here::here('data', 'public-20q3_v32-achilles-gene-effect.csv')) %>% column_to_rownames('V1') %>% extract_hugo_symbol_colnames() 

genes <- c('UBA6', 'BIRC6', 'KCMF1', 'UBR4')
ge_subset <- Achilles.gene.effect.CRISPR[, genes]
correlation = cor(ge_subset[rowSums(is.na(ge_subset))==0,])

pdf(file =here::here('output', 'Fig1', 'CRISPR_correlations.pdf'))
correlation_plot <- corrplot(correlation, method="circle", type='lower', addCoef.col='white')
dev.off()
```



## RNAi
```{r}
gene.effect.RNAi <- data.table::fread(here::here('data', 'demeter2-achilles_v12-gene-effect.csv')) %>% column_to_rownames('V1') %>% extract_hugo_symbol_colnames() 

ge_subset <- gene.effect.RNAi[, genes]
correlation = cor(ge_subset[rowSums(is.na(ge_subset))==0,])
corrplot(correlation, method="circle", type='lower', addCoef.col='white')

pdf(file =here::here('output', 'Fig1', 'RNAi_correlations.pdf'))
correlation_plot <- corrplot(correlation, method="circle", type='lower', addCoef.col='white')
dev.off()
```